beolink_join:
  target:
    entity:
      integration: bang_olufsen
      domain: media_player
    device:
      integration: bang_olufsen
  fields:
    beolink_jid:
      required: false
      example: 1111.2222222.33333333@products.bang-olufsen.com
      selector:
        text:

beolink_expand:
  target:
    entity:
      integration: bang_olufsen
      domain: media_player
    device:
      integration: bang_olufsen
  fields:
    all_discovered:
      required: false
      example: false
      selector:
        boolean:
    beolink_jids:
      required: false
      example: >-
        [
          1111.2222222.33333333@products.bang-olufsen.com,
          4444.5555555.66666666@products.bang-olufsen.com
        ]
      selector:
        object:

beolink_unexpand:
  target:
    entity:
      integration: bang_olufsen
      domain: media_player
    device:
      integration: bang_olufsen
  fields:
    beolink_jids:
      required: true
      example: >-
        [
          1111.2222222.33333333@products.bang-olufsen.com,
          4444.5555555.66666666@products.bang-olufsen.com
        ]
      selector:
        object:

beolink_leave:
  target:
    entity:
      integration: bang_olufsen
      domain: media_player
    device:
      integration: bang_olufsen

beolink_allstandby:
  target:
    entity:
      integration: bang_olufsen
      domain: media_player
    device:
      integration: bang_olufsen

beolink_set_volume:
  target:
    entity:
      integration: bang_olufsen
      domain: media_player
    device:
      integration: bang_olufsen
  fields:
    volume_level:
      required: true
      example: 0.4
      selector:
        text:

beolink_set_relative_volume:
  target:
    entity:
      integration: bang_olufsen
      domain: media_player
    device:
      integration: bang_olufsen
  fields:
    volume_level:
      required: true
      example: 0.2
      selector:
        text:

beolink_leader_command:
  target:
    entity:
      integration: bang_olufsen
      domain: media_player
    device:
      integration: bang_olufsen
  fields:
    command:
      required: true
      example: "set_volume_level"
      selector:
        select:
          options:
            - "media_next_track"
            - "media_pause"
            - "media_play_pause"
            - "media_play"
            - "media_previous_track"
            - "media_seek"
            - "media_stop"
            - "mute_volume"
            - "select_source"
            - "set_relative_volume_level"
            - "set_volume_level"
            - "toggle"
            - "volume_down"
            - "volume_up"
    parameter:
      required: false
      example: 0.4
      selector:
        text:
